import {MigrationInterface, QueryRunner} from "typeorm";

export class initDB1629926709229 implements MigrationInterface {
    name = 'initDB1629926709229'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`test2\`.\`fm_ident_type\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`test2\`.\`fm_roles\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`test2\`.\`fm_way_pay\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`test2\`.\`fm_type_request\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`test2\`.\`fm_status_request\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_request\` ADD \`id_commerce\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_request\` ADD \`id_type_request\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_request\` ADD \`fm_status_request\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_request\` ADD \`idWayPayId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_request\` ADD UNIQUE INDEX \`IDX_af880b2a93f79cc4377ab8c7ac\` (\`idWayPayId\`)`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_request\` ADD \`idCommerceId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_phone\` DROP FOREIGN KEY \`FK_c6e07f1585b1805268c9c6584a5\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_phone\` CHANGE \`idClientId\` \`idClientId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_request\` DROP FOREIGN KEY \`FK_1134cd317f45c6a39458764451b\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_request\` CHANGE \`idClientId\` \`idClientId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_ciudad\` DROP FOREIGN KEY \`FK_06b45182e630a7a33123d77b6c6\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_ciudad\` CHANGE \`idEstadoId\` \`idEstadoId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_parroquia\` DROP FOREIGN KEY \`FK_9f3024408c0cb02a72e0898be67\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_parroquia\` CHANGE \`idMunicipioId\` \`idMunicipioId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_municipio\` DROP FOREIGN KEY \`FK_c2952f0ade0c768923bfcd091e1\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_municipio\` CHANGE \`idEstadoId\` \`idEstadoId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_location\` DROP FOREIGN KEY \`FK_7faad64c4d276d229d45585e99c\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_location\` DROP FOREIGN KEY \`FK_e68b330dedc0ef489fa8b4d4235\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_location\` DROP FOREIGN KEY \`FK_77a478bbe486ef168042ef77099\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_location\` DROP FOREIGN KEY \`FK_681edb0782ea058000073db6f41\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_location\` DROP FOREIGN KEY \`FK_1958317995d7b21b3174f67f89f\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_location\` CHANGE \`idEstadoId\` \`idEstadoId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_location\` CHANGE \`idMunicipioId\` \`idMunicipioId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_location\` CHANGE \`idCiudadId\` \`idCiudadId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_location\` CHANGE \`idParroquiaId\` \`idParroquiaId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_location\` CHANGE \`idCodPostalId\` \`idCodPostalId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_dir_post\` DROP FOREIGN KEY \`FK_91fc4ff405576c467174ba99488\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_dir_post\` DROP FOREIGN KEY \`FK_e1db58f255fe5ca787974f4b023\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_dir_post\` CHANGE \`idLocationId\` \`idLocationId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_dir_post\` CHANGE \`idCommerceId\` \`idCommerceId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_commerce\` DROP FOREIGN KEY \`FK_196bd8fe75da538dc9d94435666\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_commerce\` DROP FOREIGN KEY \`FK_8531fcd1168b00dc828cd075aac\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_commerce\` DROP FOREIGN KEY \`FK_d15fa48b2e2917bbad5ca93f0b9\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_commerce\` CHANGE \`idActivityId\` \`idActivityId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_commerce\` CHANGE \`idAciId\` \`idAciId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_commerce\` CHANGE \`idClientId\` \`idClientId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_bank_commerce\` DROP FOREIGN KEY \`FK_4fdb498852192b9992039cf9dc8\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_bank_commerce\` DROP FOREIGN KEY \`FK_7aca6edbc077a370a90dde3a3da\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_bank_commerce\` CHANGE \`idCommerceId\` \`idCommerceId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_bank_commerce\` CHANGE \`idBankId\` \`idBankId\` int NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_af880b2a93f79cc4377ab8c7ac\` ON \`test2\`.\`fm_request\` (\`idWayPayId\`)`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_phone\` ADD CONSTRAINT \`FK_c6e07f1585b1805268c9c6584a5\` FOREIGN KEY (\`idClientId\`) REFERENCES \`test2\`.\`fm_clinet\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_request\` ADD CONSTRAINT \`FK_af880b2a93f79cc4377ab8c7ac7\` FOREIGN KEY (\`idWayPayId\`) REFERENCES \`test2\`.\`fm_way_pay\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_request\` ADD CONSTRAINT \`FK_1134cd317f45c6a39458764451b\` FOREIGN KEY (\`idClientId\`) REFERENCES \`test2\`.\`fm_clinet\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_request\` ADD CONSTRAINT \`FK_4634fa27193bcbbe0e27d909385\` FOREIGN KEY (\`idCommerceId\`) REFERENCES \`test2\`.\`fm_commerce\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_ciudad\` ADD CONSTRAINT \`FK_06b45182e630a7a33123d77b6c6\` FOREIGN KEY (\`idEstadoId\`) REFERENCES \`test2\`.\`fm_estado\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_parroquia\` ADD CONSTRAINT \`FK_9f3024408c0cb02a72e0898be67\` FOREIGN KEY (\`idMunicipioId\`) REFERENCES \`test2\`.\`fm_municipio\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_municipio\` ADD CONSTRAINT \`FK_c2952f0ade0c768923bfcd091e1\` FOREIGN KEY (\`idEstadoId\`) REFERENCES \`test2\`.\`fm_estado\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_location\` ADD CONSTRAINT \`FK_7faad64c4d276d229d45585e99c\` FOREIGN KEY (\`idEstadoId\`) REFERENCES \`test2\`.\`fm_estado\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_location\` ADD CONSTRAINT \`FK_e68b330dedc0ef489fa8b4d4235\` FOREIGN KEY (\`idMunicipioId\`) REFERENCES \`test2\`.\`fm_municipio\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_location\` ADD CONSTRAINT \`FK_77a478bbe486ef168042ef77099\` FOREIGN KEY (\`idCiudadId\`) REFERENCES \`test2\`.\`fm_ciudad\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_location\` ADD CONSTRAINT \`FK_681edb0782ea058000073db6f41\` FOREIGN KEY (\`idParroquiaId\`) REFERENCES \`test2\`.\`fm_parroquia\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_location\` ADD CONSTRAINT \`FK_1958317995d7b21b3174f67f89f\` FOREIGN KEY (\`idCodPostalId\`) REFERENCES \`test2\`.\`fm_cod_postal\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_dir_post\` ADD CONSTRAINT \`FK_91fc4ff405576c467174ba99488\` FOREIGN KEY (\`idLocationId\`) REFERENCES \`test2\`.\`fm_location\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_dir_post\` ADD CONSTRAINT \`FK_e1db58f255fe5ca787974f4b023\` FOREIGN KEY (\`idCommerceId\`) REFERENCES \`test2\`.\`fm_commerce\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_commerce\` ADD CONSTRAINT \`FK_196bd8fe75da538dc9d94435666\` FOREIGN KEY (\`idActivityId\`) REFERENCES \`test2\`.\`fm_activity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_commerce\` ADD CONSTRAINT \`FK_8531fcd1168b00dc828cd075aac\` FOREIGN KEY (\`idAciId\`) REFERENCES \`test2\`.\`fm_worker\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_commerce\` ADD CONSTRAINT \`FK_d15fa48b2e2917bbad5ca93f0b9\` FOREIGN KEY (\`idClientId\`) REFERENCES \`test2\`.\`fm_clinet\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_bank_commerce\` ADD CONSTRAINT \`FK_4fdb498852192b9992039cf9dc8\` FOREIGN KEY (\`idCommerceId\`) REFERENCES \`test2\`.\`fm_commerce\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_bank_commerce\` ADD CONSTRAINT \`FK_7aca6edbc077a370a90dde3a3da\` FOREIGN KEY (\`idBankId\`) REFERENCES \`test2\`.\`fm_bank\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_bank_commerce\` DROP FOREIGN KEY \`FK_7aca6edbc077a370a90dde3a3da\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_bank_commerce\` DROP FOREIGN KEY \`FK_4fdb498852192b9992039cf9dc8\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_commerce\` DROP FOREIGN KEY \`FK_d15fa48b2e2917bbad5ca93f0b9\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_commerce\` DROP FOREIGN KEY \`FK_8531fcd1168b00dc828cd075aac\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_commerce\` DROP FOREIGN KEY \`FK_196bd8fe75da538dc9d94435666\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_dir_post\` DROP FOREIGN KEY \`FK_e1db58f255fe5ca787974f4b023\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_dir_post\` DROP FOREIGN KEY \`FK_91fc4ff405576c467174ba99488\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_location\` DROP FOREIGN KEY \`FK_1958317995d7b21b3174f67f89f\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_location\` DROP FOREIGN KEY \`FK_681edb0782ea058000073db6f41\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_location\` DROP FOREIGN KEY \`FK_77a478bbe486ef168042ef77099\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_location\` DROP FOREIGN KEY \`FK_e68b330dedc0ef489fa8b4d4235\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_location\` DROP FOREIGN KEY \`FK_7faad64c4d276d229d45585e99c\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_municipio\` DROP FOREIGN KEY \`FK_c2952f0ade0c768923bfcd091e1\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_parroquia\` DROP FOREIGN KEY \`FK_9f3024408c0cb02a72e0898be67\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_ciudad\` DROP FOREIGN KEY \`FK_06b45182e630a7a33123d77b6c6\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_request\` DROP FOREIGN KEY \`FK_4634fa27193bcbbe0e27d909385\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_request\` DROP FOREIGN KEY \`FK_1134cd317f45c6a39458764451b\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_request\` DROP FOREIGN KEY \`FK_af880b2a93f79cc4377ab8c7ac7\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_phone\` DROP FOREIGN KEY \`FK_c6e07f1585b1805268c9c6584a5\``);
        await queryRunner.query(`DROP INDEX \`REL_af880b2a93f79cc4377ab8c7ac\` ON \`test2\`.\`fm_request\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_bank_commerce\` CHANGE \`idBankId\` \`idBankId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_bank_commerce\` CHANGE \`idCommerceId\` \`idCommerceId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_bank_commerce\` ADD CONSTRAINT \`FK_7aca6edbc077a370a90dde3a3da\` FOREIGN KEY (\`idBankId\`) REFERENCES \`test2\`.\`fm_bank\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_bank_commerce\` ADD CONSTRAINT \`FK_4fdb498852192b9992039cf9dc8\` FOREIGN KEY (\`idCommerceId\`) REFERENCES \`test2\`.\`fm_commerce\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_commerce\` CHANGE \`idClientId\` \`idClientId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_commerce\` CHANGE \`idAciId\` \`idAciId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_commerce\` CHANGE \`idActivityId\` \`idActivityId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_commerce\` ADD CONSTRAINT \`FK_d15fa48b2e2917bbad5ca93f0b9\` FOREIGN KEY (\`idClientId\`) REFERENCES \`test2\`.\`fm_clinet\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_commerce\` ADD CONSTRAINT \`FK_8531fcd1168b00dc828cd075aac\` FOREIGN KEY (\`idAciId\`) REFERENCES \`test2\`.\`fm_worker\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_commerce\` ADD CONSTRAINT \`FK_196bd8fe75da538dc9d94435666\` FOREIGN KEY (\`idActivityId\`) REFERENCES \`test2\`.\`fm_activity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_dir_post\` CHANGE \`idCommerceId\` \`idCommerceId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_dir_post\` CHANGE \`idLocationId\` \`idLocationId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_dir_post\` ADD CONSTRAINT \`FK_e1db58f255fe5ca787974f4b023\` FOREIGN KEY (\`idCommerceId\`) REFERENCES \`test2\`.\`fm_commerce\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_dir_post\` ADD CONSTRAINT \`FK_91fc4ff405576c467174ba99488\` FOREIGN KEY (\`idLocationId\`) REFERENCES \`test2\`.\`fm_location\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_location\` CHANGE \`idCodPostalId\` \`idCodPostalId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_location\` CHANGE \`idParroquiaId\` \`idParroquiaId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_location\` CHANGE \`idCiudadId\` \`idCiudadId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_location\` CHANGE \`idMunicipioId\` \`idMunicipioId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_location\` CHANGE \`idEstadoId\` \`idEstadoId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_location\` ADD CONSTRAINT \`FK_1958317995d7b21b3174f67f89f\` FOREIGN KEY (\`idCodPostalId\`) REFERENCES \`test2\`.\`fm_cod_postal\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_location\` ADD CONSTRAINT \`FK_681edb0782ea058000073db6f41\` FOREIGN KEY (\`idParroquiaId\`) REFERENCES \`test2\`.\`fm_parroquia\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_location\` ADD CONSTRAINT \`FK_77a478bbe486ef168042ef77099\` FOREIGN KEY (\`idCiudadId\`) REFERENCES \`test2\`.\`fm_ciudad\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_location\` ADD CONSTRAINT \`FK_e68b330dedc0ef489fa8b4d4235\` FOREIGN KEY (\`idMunicipioId\`) REFERENCES \`test2\`.\`fm_municipio\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_location\` ADD CONSTRAINT \`FK_7faad64c4d276d229d45585e99c\` FOREIGN KEY (\`idEstadoId\`) REFERENCES \`test2\`.\`fm_estado\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_municipio\` CHANGE \`idEstadoId\` \`idEstadoId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_municipio\` ADD CONSTRAINT \`FK_c2952f0ade0c768923bfcd091e1\` FOREIGN KEY (\`idEstadoId\`) REFERENCES \`test2\`.\`fm_estado\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_parroquia\` CHANGE \`idMunicipioId\` \`idMunicipioId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_parroquia\` ADD CONSTRAINT \`FK_9f3024408c0cb02a72e0898be67\` FOREIGN KEY (\`idMunicipioId\`) REFERENCES \`test2\`.\`fm_municipio\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_ciudad\` CHANGE \`idEstadoId\` \`idEstadoId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_ciudad\` ADD CONSTRAINT \`FK_06b45182e630a7a33123d77b6c6\` FOREIGN KEY (\`idEstadoId\`) REFERENCES \`test2\`.\`fm_estado\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_request\` CHANGE \`idClientId\` \`idClientId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_request\` ADD CONSTRAINT \`FK_1134cd317f45c6a39458764451b\` FOREIGN KEY (\`idClientId\`) REFERENCES \`test2\`.\`fm_clinet\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_phone\` CHANGE \`idClientId\` \`idClientId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_phone\` ADD CONSTRAINT \`FK_c6e07f1585b1805268c9c6584a5\` FOREIGN KEY (\`idClientId\`) REFERENCES \`test2\`.\`fm_clinet\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_request\` DROP COLUMN \`idCommerceId\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_request\` DROP INDEX \`IDX_af880b2a93f79cc4377ab8c7ac\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_request\` DROP COLUMN \`idWayPayId\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_request\` DROP COLUMN \`fm_status_request\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_request\` DROP COLUMN \`id_type_request\``);
        await queryRunner.query(`ALTER TABLE \`test2\`.\`fm_request\` DROP COLUMN \`id_commerce\``);
        await queryRunner.query(`DROP TABLE \`test2\`.\`fm_status_request\``);
        await queryRunner.query(`DROP TABLE \`test2\`.\`fm_type_request\``);
        await queryRunner.query(`DROP TABLE \`test2\`.\`fm_way_pay\``);
        await queryRunner.query(`DROP TABLE \`test2\`.\`fm_roles\``);
        await queryRunner.query(`DROP TABLE \`test2\`.\`fm_ident_type\``);
    }

}
