import {MigrationInterface, QueryRunner} from "typeorm";

export class initDB1630520275493 implements MigrationInterface {
    name = 'initDB1630520275493'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_worker\` DROP FOREIGN KEY \`FK_e018746d22c55fc0477298963ad\``);
        await queryRunner.query(`DROP INDEX \`IDX_7a21b1b04b3df8909ad71d8909\` ON \`1000pagosdev\`.\`fm_worker\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_worker\` CHANGE \`id_ident_type\` \`id_ident_type\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_phone\` DROP FOREIGN KEY \`FK_3796c0f20cddbfce6840776200f\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_phone\` CHANGE \`id_client\` \`id_client\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_af1eae98b17fa9e92881cafce3d\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_5a70c1436abb7fb7bb081bd667e\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_784d15eaace1537f9f699aff258\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_b5772edefef68ff71c6477c9705\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_4f207c9a0e9645910383377f86d\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_ecb3a612691fb1e01af12683e37\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_4668ebbef8614032e9d58794d46\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_dd9755e9774701f02578f7658bd\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_75608537a84bc5097f4c5635e03\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_395407df85335f0e00430aa3876\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_9dd51a6b0f9bc09cd820b0c8076\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_7af3f0d3b144b7d6a72ceac4073\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_bd495da93173bc09fe6d62b98b5\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_96c58e4419abc60056da31ef769\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_8e6a76c31cf8fb8ef74f4823e10\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_1be6883cd897407227f6f434422\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`rc_constitutive_act\` \`rc_constitutive_act\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`rc_property_document\` \`rc_property_document\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`rc_service_document\` \`rc_service_document\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`rc_special_contributor\` \`rc_special_contributor\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`rc_ref_bank\` \`rc_ref_bank\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`rc_ref_perso\` \`rc_ref_perso\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`rc_account_number\` \`rc_account_number\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`rc_front_local\` \`rc_front_local\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`rc_in_local\` \`rc_in_local\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`rc_rif\` \`rc_rif\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`rc_ident_card\` \`rc_ident_card\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`id_payment_method\` \`id_payment_method\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`id_client\` \`id_client\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`id_commerce\` \`id_commerce\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`id_type_request\` \`id_type_request\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`fm_status_request\` \`fm_status_request\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_client\` DROP FOREIGN KEY \`FK_a4d752b12018c7ffc6a64a65307\``);
        await queryRunner.query(`DROP INDEX \`IDX_15f756dc2a9a6aefe1751f731f\` ON \`1000pagosdev\`.\`fm_client\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_client\` CHANGE \`id_ident_type\` \`id_ident_type\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_ciudad\` DROP FOREIGN KEY \`FK_41e29c427582948e763288142c1\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_ciudad\` CHANGE \`id_estado\` \`id_estado\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_parroquia\` DROP FOREIGN KEY \`FK_4ac1c804b1f8dcfc3b08363151f\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_parroquia\` CHANGE \`id_municipio\` \`id_municipio\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_municipio\` DROP FOREIGN KEY \`FK_9210306e682154252390bb45859\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_municipio\` CHANGE \`id_estado\` \`id_estado\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` DROP FOREIGN KEY \`FK_61ea978348ae6a36894bd39de24\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` DROP FOREIGN KEY \`FK_1c57c6523dd537b0ef0a9f5b419\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` DROP FOREIGN KEY \`FK_3e940da713ea86a9367f70618d0\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` DROP FOREIGN KEY \`FK_73174abf588e8edc848e2e3a121\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` CHANGE \`id_estado\` \`id_estado\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` CHANGE \`id_municipio\` \`id_municipio\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` CHANGE \`id_ciudad\` \`id_ciudad\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` CHANGE \`id_parroquia\` \`id_parroquia\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_dir_post\` DROP FOREIGN KEY \`FK_015c3b2143094f7b284500f049d\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_dir_post\` DROP FOREIGN KEY \`FK_deac441944a320c379e0f1b1d5d\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_dir_post\` CHANGE \`id_location\` \`id_location\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_dir_post\` CHANGE \`id_commerce\` \`id_commerce\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` DROP FOREIGN KEY \`FK_9d10e9066e2a479adcf4830e65b\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` DROP FOREIGN KEY \`FK_ae4a2f524f6c29e5d38f265f7ac\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` CHANGE \`id_activity\` \`id_activity\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` CHANGE \`id_client\` \`id_client\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_bank_commerce\` DROP FOREIGN KEY \`FK_f6a998bb3ed4eb4c244b9baa7f3\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_bank_commerce\` DROP FOREIGN KEY \`FK_ac51278339d6ed7a4bcbb5bda7f\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_bank_commerce\` CHANGE \`id_commerce\` \`id_commerce\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_bank_commerce\` CHANGE \`id_bank\` \`id_bank\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_product\` DROP FOREIGN KEY \`FK_cc8feb26b45d579f0f7372aca66\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_product\` CHANGE \`id_paym_method\` \`id_paym_method\` int NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_7a21b1b04b3df8909ad71d8909\` ON \`1000pagosdev\`.\`fm_worker\` (\`id_ident_type\`, \`ident_num\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_15f756dc2a9a6aefe1751f731f\` ON \`1000pagosdev\`.\`fm_client\` (\`id_ident_type\`, \`ident_num\`)`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_worker\` ADD CONSTRAINT \`FK_e018746d22c55fc0477298963ad\` FOREIGN KEY (\`id_ident_type\`) REFERENCES \`1000pagosdev\`.\`fm_ident_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_phone\` ADD CONSTRAINT \`FK_3796c0f20cddbfce6840776200f\` FOREIGN KEY (\`id_client\`) REFERENCES \`1000pagosdev\`.\`fm_client\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_af1eae98b17fa9e92881cafce3d\` FOREIGN KEY (\`rc_constitutive_act\`) REFERENCES \`1000pagosdev\`.\`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_5a70c1436abb7fb7bb081bd667e\` FOREIGN KEY (\`rc_property_document\`) REFERENCES \`1000pagosdev\`.\`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_784d15eaace1537f9f699aff258\` FOREIGN KEY (\`rc_service_document\`) REFERENCES \`1000pagosdev\`.\`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_b5772edefef68ff71c6477c9705\` FOREIGN KEY (\`rc_special_contributor\`) REFERENCES \`1000pagosdev\`.\`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_4f207c9a0e9645910383377f86d\` FOREIGN KEY (\`rc_ref_bank\`) REFERENCES \`1000pagosdev\`.\`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_ecb3a612691fb1e01af12683e37\` FOREIGN KEY (\`rc_ref_perso\`) REFERENCES \`1000pagosdev\`.\`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_4668ebbef8614032e9d58794d46\` FOREIGN KEY (\`rc_account_number\`) REFERENCES \`1000pagosdev\`.\`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_dd9755e9774701f02578f7658bd\` FOREIGN KEY (\`rc_front_local\`) REFERENCES \`1000pagosdev\`.\`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_75608537a84bc5097f4c5635e03\` FOREIGN KEY (\`rc_in_local\`) REFERENCES \`1000pagosdev\`.\`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_395407df85335f0e00430aa3876\` FOREIGN KEY (\`rc_rif\`) REFERENCES \`1000pagosdev\`.\`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_9dd51a6b0f9bc09cd820b0c8076\` FOREIGN KEY (\`rc_ident_card\`) REFERENCES \`1000pagosdev\`.\`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_7af3f0d3b144b7d6a72ceac4073\` FOREIGN KEY (\`id_payment_method\`) REFERENCES \`1000pagosdev\`.\`fm_payment_method\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_bd495da93173bc09fe6d62b98b5\` FOREIGN KEY (\`id_client\`) REFERENCES \`1000pagosdev\`.\`fm_client\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_96c58e4419abc60056da31ef769\` FOREIGN KEY (\`id_commerce\`) REFERENCES \`1000pagosdev\`.\`fm_commerce\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_8e6a76c31cf8fb8ef74f4823e10\` FOREIGN KEY (\`id_type_request\`) REFERENCES \`1000pagosdev\`.\`fm_type_request\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_1be6883cd897407227f6f434422\` FOREIGN KEY (\`fm_status_request\`) REFERENCES \`1000pagosdev\`.\`fm_status_request\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_client\` ADD CONSTRAINT \`FK_a4d752b12018c7ffc6a64a65307\` FOREIGN KEY (\`id_ident_type\`) REFERENCES \`1000pagosdev\`.\`fm_ident_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_ciudad\` ADD CONSTRAINT \`FK_41e29c427582948e763288142c1\` FOREIGN KEY (\`id_estado\`) REFERENCES \`1000pagosdev\`.\`fm_estado\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_parroquia\` ADD CONSTRAINT \`FK_4ac1c804b1f8dcfc3b08363151f\` FOREIGN KEY (\`id_municipio\`) REFERENCES \`1000pagosdev\`.\`fm_municipio\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_municipio\` ADD CONSTRAINT \`FK_9210306e682154252390bb45859\` FOREIGN KEY (\`id_estado\`) REFERENCES \`1000pagosdev\`.\`fm_estado\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` ADD CONSTRAINT \`FK_61ea978348ae6a36894bd39de24\` FOREIGN KEY (\`id_estado\`) REFERENCES \`1000pagosdev\`.\`fm_estado\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` ADD CONSTRAINT \`FK_1c57c6523dd537b0ef0a9f5b419\` FOREIGN KEY (\`id_municipio\`) REFERENCES \`1000pagosdev\`.\`fm_municipio\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` ADD CONSTRAINT \`FK_3e940da713ea86a9367f70618d0\` FOREIGN KEY (\`id_ciudad\`) REFERENCES \`1000pagosdev\`.\`fm_ciudad\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` ADD CONSTRAINT \`FK_73174abf588e8edc848e2e3a121\` FOREIGN KEY (\`id_parroquia\`) REFERENCES \`1000pagosdev\`.\`fm_parroquia\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_dir_post\` ADD CONSTRAINT \`FK_015c3b2143094f7b284500f049d\` FOREIGN KEY (\`id_location\`) REFERENCES \`1000pagosdev\`.\`fm_location\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_dir_post\` ADD CONSTRAINT \`FK_deac441944a320c379e0f1b1d5d\` FOREIGN KEY (\`id_commerce\`) REFERENCES \`1000pagosdev\`.\`fm_commerce\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` ADD CONSTRAINT \`FK_9d10e9066e2a479adcf4830e65b\` FOREIGN KEY (\`id_activity\`) REFERENCES \`1000pagosdev\`.\`fm_activity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` ADD CONSTRAINT \`FK_ae4a2f524f6c29e5d38f265f7ac\` FOREIGN KEY (\`id_client\`) REFERENCES \`1000pagosdev\`.\`fm_client\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_bank_commerce\` ADD CONSTRAINT \`FK_f6a998bb3ed4eb4c244b9baa7f3\` FOREIGN KEY (\`id_commerce\`) REFERENCES \`1000pagosdev\`.\`fm_commerce\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_bank_commerce\` ADD CONSTRAINT \`FK_ac51278339d6ed7a4bcbb5bda7f\` FOREIGN KEY (\`id_bank\`) REFERENCES \`1000pagosdev\`.\`fm_bank\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_product\` ADD CONSTRAINT \`FK_cc8feb26b45d579f0f7372aca66\` FOREIGN KEY (\`id_paym_method\`) REFERENCES \`1000pagosdev\`.\`fm_payment_method\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_product\` DROP FOREIGN KEY \`FK_cc8feb26b45d579f0f7372aca66\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_bank_commerce\` DROP FOREIGN KEY \`FK_ac51278339d6ed7a4bcbb5bda7f\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_bank_commerce\` DROP FOREIGN KEY \`FK_f6a998bb3ed4eb4c244b9baa7f3\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` DROP FOREIGN KEY \`FK_ae4a2f524f6c29e5d38f265f7ac\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` DROP FOREIGN KEY \`FK_9d10e9066e2a479adcf4830e65b\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_dir_post\` DROP FOREIGN KEY \`FK_deac441944a320c379e0f1b1d5d\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_dir_post\` DROP FOREIGN KEY \`FK_015c3b2143094f7b284500f049d\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` DROP FOREIGN KEY \`FK_73174abf588e8edc848e2e3a121\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` DROP FOREIGN KEY \`FK_3e940da713ea86a9367f70618d0\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` DROP FOREIGN KEY \`FK_1c57c6523dd537b0ef0a9f5b419\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` DROP FOREIGN KEY \`FK_61ea978348ae6a36894bd39de24\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_municipio\` DROP FOREIGN KEY \`FK_9210306e682154252390bb45859\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_parroquia\` DROP FOREIGN KEY \`FK_4ac1c804b1f8dcfc3b08363151f\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_ciudad\` DROP FOREIGN KEY \`FK_41e29c427582948e763288142c1\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_client\` DROP FOREIGN KEY \`FK_a4d752b12018c7ffc6a64a65307\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_1be6883cd897407227f6f434422\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_8e6a76c31cf8fb8ef74f4823e10\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_96c58e4419abc60056da31ef769\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_bd495da93173bc09fe6d62b98b5\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_7af3f0d3b144b7d6a72ceac4073\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_9dd51a6b0f9bc09cd820b0c8076\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_395407df85335f0e00430aa3876\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_75608537a84bc5097f4c5635e03\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_dd9755e9774701f02578f7658bd\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_4668ebbef8614032e9d58794d46\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_ecb3a612691fb1e01af12683e37\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_4f207c9a0e9645910383377f86d\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_b5772edefef68ff71c6477c9705\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_784d15eaace1537f9f699aff258\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_5a70c1436abb7fb7bb081bd667e\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_af1eae98b17fa9e92881cafce3d\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_phone\` DROP FOREIGN KEY \`FK_3796c0f20cddbfce6840776200f\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_worker\` DROP FOREIGN KEY \`FK_e018746d22c55fc0477298963ad\``);
        await queryRunner.query(`DROP INDEX \`IDX_15f756dc2a9a6aefe1751f731f\` ON \`1000pagosdev\`.\`fm_client\``);
        await queryRunner.query(`DROP INDEX \`IDX_7a21b1b04b3df8909ad71d8909\` ON \`1000pagosdev\`.\`fm_worker\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_product\` CHANGE \`id_paym_method\` \`id_paym_method\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_product\` ADD CONSTRAINT \`FK_cc8feb26b45d579f0f7372aca66\` FOREIGN KEY (\`id_paym_method\`) REFERENCES \`1000pagosdev\`.\`fm_payment_method\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_bank_commerce\` CHANGE \`id_bank\` \`id_bank\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_bank_commerce\` CHANGE \`id_commerce\` \`id_commerce\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_bank_commerce\` ADD CONSTRAINT \`FK_ac51278339d6ed7a4bcbb5bda7f\` FOREIGN KEY (\`id_bank\`) REFERENCES \`1000pagosdev\`.\`fm_bank\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_bank_commerce\` ADD CONSTRAINT \`FK_f6a998bb3ed4eb4c244b9baa7f3\` FOREIGN KEY (\`id_commerce\`) REFERENCES \`1000pagosdev\`.\`fm_commerce\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` CHANGE \`id_client\` \`id_client\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` CHANGE \`id_activity\` \`id_activity\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` ADD CONSTRAINT \`FK_ae4a2f524f6c29e5d38f265f7ac\` FOREIGN KEY (\`id_client\`) REFERENCES \`1000pagosdev\`.\`fm_client\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` ADD CONSTRAINT \`FK_9d10e9066e2a479adcf4830e65b\` FOREIGN KEY (\`id_activity\`) REFERENCES \`1000pagosdev\`.\`fm_activity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_dir_post\` CHANGE \`id_commerce\` \`id_commerce\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_dir_post\` CHANGE \`id_location\` \`id_location\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_dir_post\` ADD CONSTRAINT \`FK_deac441944a320c379e0f1b1d5d\` FOREIGN KEY (\`id_commerce\`) REFERENCES \`1000pagosdev\`.\`fm_commerce\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_dir_post\` ADD CONSTRAINT \`FK_015c3b2143094f7b284500f049d\` FOREIGN KEY (\`id_location\`) REFERENCES \`1000pagosdev\`.\`fm_location\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` CHANGE \`id_parroquia\` \`id_parroquia\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` CHANGE \`id_ciudad\` \`id_ciudad\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` CHANGE \`id_municipio\` \`id_municipio\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` CHANGE \`id_estado\` \`id_estado\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` ADD CONSTRAINT \`FK_73174abf588e8edc848e2e3a121\` FOREIGN KEY (\`id_parroquia\`) REFERENCES \`1000pagosdev\`.\`fm_parroquia\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` ADD CONSTRAINT \`FK_3e940da713ea86a9367f70618d0\` FOREIGN KEY (\`id_ciudad\`) REFERENCES \`1000pagosdev\`.\`fm_ciudad\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` ADD CONSTRAINT \`FK_1c57c6523dd537b0ef0a9f5b419\` FOREIGN KEY (\`id_municipio\`) REFERENCES \`1000pagosdev\`.\`fm_municipio\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` ADD CONSTRAINT \`FK_61ea978348ae6a36894bd39de24\` FOREIGN KEY (\`id_estado\`) REFERENCES \`1000pagosdev\`.\`fm_estado\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_municipio\` CHANGE \`id_estado\` \`id_estado\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_municipio\` ADD CONSTRAINT \`FK_9210306e682154252390bb45859\` FOREIGN KEY (\`id_estado\`) REFERENCES \`1000pagosdev\`.\`fm_estado\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_parroquia\` CHANGE \`id_municipio\` \`id_municipio\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_parroquia\` ADD CONSTRAINT \`FK_4ac1c804b1f8dcfc3b08363151f\` FOREIGN KEY (\`id_municipio\`) REFERENCES \`1000pagosdev\`.\`fm_municipio\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_ciudad\` CHANGE \`id_estado\` \`id_estado\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_ciudad\` ADD CONSTRAINT \`FK_41e29c427582948e763288142c1\` FOREIGN KEY (\`id_estado\`) REFERENCES \`1000pagosdev\`.\`fm_estado\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_client\` CHANGE \`id_ident_type\` \`id_ident_type\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_15f756dc2a9a6aefe1751f731f\` ON \`1000pagosdev\`.\`fm_client\` (\`id_ident_type\`, \`ident_num\`)`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_client\` ADD CONSTRAINT \`FK_a4d752b12018c7ffc6a64a65307\` FOREIGN KEY (\`id_ident_type\`) REFERENCES \`1000pagosdev\`.\`fm_ident_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`fm_status_request\` \`fm_status_request\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`id_type_request\` \`id_type_request\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`id_commerce\` \`id_commerce\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`id_client\` \`id_client\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`id_payment_method\` \`id_payment_method\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`rc_ident_card\` \`rc_ident_card\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`rc_rif\` \`rc_rif\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`rc_in_local\` \`rc_in_local\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`rc_front_local\` \`rc_front_local\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`rc_account_number\` \`rc_account_number\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`rc_ref_perso\` \`rc_ref_perso\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`rc_ref_bank\` \`rc_ref_bank\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`rc_special_contributor\` \`rc_special_contributor\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`rc_service_document\` \`rc_service_document\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`rc_property_document\` \`rc_property_document\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`rc_constitutive_act\` \`rc_constitutive_act\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_1be6883cd897407227f6f434422\` FOREIGN KEY (\`fm_status_request\`) REFERENCES \`1000pagosdev\`.\`fm_status_request\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_8e6a76c31cf8fb8ef74f4823e10\` FOREIGN KEY (\`id_type_request\`) REFERENCES \`1000pagosdev\`.\`fm_type_request\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_96c58e4419abc60056da31ef769\` FOREIGN KEY (\`id_commerce\`) REFERENCES \`1000pagosdev\`.\`fm_commerce\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_bd495da93173bc09fe6d62b98b5\` FOREIGN KEY (\`id_client\`) REFERENCES \`1000pagosdev\`.\`fm_client\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_7af3f0d3b144b7d6a72ceac4073\` FOREIGN KEY (\`id_payment_method\`) REFERENCES \`1000pagosdev\`.\`fm_payment_method\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_9dd51a6b0f9bc09cd820b0c8076\` FOREIGN KEY (\`rc_ident_card\`) REFERENCES \`1000pagosdev\`.\`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_395407df85335f0e00430aa3876\` FOREIGN KEY (\`rc_rif\`) REFERENCES \`1000pagosdev\`.\`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_75608537a84bc5097f4c5635e03\` FOREIGN KEY (\`rc_in_local\`) REFERENCES \`1000pagosdev\`.\`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_dd9755e9774701f02578f7658bd\` FOREIGN KEY (\`rc_front_local\`) REFERENCES \`1000pagosdev\`.\`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_4668ebbef8614032e9d58794d46\` FOREIGN KEY (\`rc_account_number\`) REFERENCES \`1000pagosdev\`.\`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_ecb3a612691fb1e01af12683e37\` FOREIGN KEY (\`rc_ref_perso\`) REFERENCES \`1000pagosdev\`.\`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_4f207c9a0e9645910383377f86d\` FOREIGN KEY (\`rc_ref_bank\`) REFERENCES \`1000pagosdev\`.\`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_b5772edefef68ff71c6477c9705\` FOREIGN KEY (\`rc_special_contributor\`) REFERENCES \`1000pagosdev\`.\`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_784d15eaace1537f9f699aff258\` FOREIGN KEY (\`rc_service_document\`) REFERENCES \`1000pagosdev\`.\`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_5a70c1436abb7fb7bb081bd667e\` FOREIGN KEY (\`rc_property_document\`) REFERENCES \`1000pagosdev\`.\`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_af1eae98b17fa9e92881cafce3d\` FOREIGN KEY (\`rc_constitutive_act\`) REFERENCES \`1000pagosdev\`.\`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_phone\` CHANGE \`id_client\` \`id_client\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_phone\` ADD CONSTRAINT \`FK_3796c0f20cddbfce6840776200f\` FOREIGN KEY (\`id_client\`) REFERENCES \`1000pagosdev\`.\`fm_client\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_worker\` CHANGE \`id_ident_type\` \`id_ident_type\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_7a21b1b04b3df8909ad71d8909\` ON \`1000pagosdev\`.\`fm_worker\` (\`id_ident_type\`, \`ident_num\`)`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_worker\` ADD CONSTRAINT \`FK_e018746d22c55fc0477298963ad\` FOREIGN KEY (\`id_ident_type\`) REFERENCES \`1000pagosdev\`.\`fm_ident_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
