import {MigrationInterface, QueryRunner} from "typeorm";

export class initDB1630080256372 implements MigrationInterface {
    name = 'initDB1630080256372'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_activity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_bank\` (\`id\` int NOT NULL AUTO_INCREMENT, \`code\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_ident_type\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_roles\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_department\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_worker\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`last_name\` varchar(255) NOT NULL, \`id_roles\` int NOT NULL DEFAULT '2', \`password\` varchar(255) NOT NULL, \`ident_num\` varchar(255) NOT NULL, \`email\` varchar(255) NOT NULL, \`phone\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`idIdentTypeId\` int NULL, UNIQUE INDEX \`IDX_116ab774592bca9d98010aa4c3\` (\`idIdentTypeId\`, \`ident_num\`), UNIQUE INDEX \`IDX_35eb1f25e7bf89140a2c986b07\` (\`email\`), UNIQUE INDEX \`REL_65a70eeb0fb74c503ed15f1064\` (\`idIdentTypeId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_phone\` (\`id\` int NOT NULL AUTO_INCREMENT, \`phone\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`idClientId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_payment_method\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_type_request\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_status_request\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_request\` (\`id\` int NOT NULL AUTO_INCREMENT, \`number_post\` int NOT NULL, \`rc_constitutive_act\` varchar(255) NOT NULL, \`rc_property_document\` varchar(255) NOT NULL, \`rc_service_document\` varchar(255) NOT NULL, \`rc_special_contributor\` varchar(255) NOT NULL, \`rc_ref_bank\` varchar(255) NOT NULL, \`rc_ref_perso\` varchar(255) NOT NULL, \`rc_account_number\` varchar(255) NOT NULL, \`text_account_number\` varchar(255) NOT NULL, \`rc_front_local\` varchar(255) NOT NULL, \`rc_in_local\` varchar(255) NOT NULL, \`rc_rif\` varchar(255) NOT NULL, \`rc_ident_card\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`idPaymentMethodId\` int NULL, \`idClientId\` int NULL, \`idCommerceId\` int NULL, \`idTypeRequestId\` int NULL, \`fmStatusRequestId\` int NULL, UNIQUE INDEX \`REL_6c23e4e82323cd84ea108afb6e\` (\`idPaymentMethodId\`), UNIQUE INDEX \`REL_38f1e43facd2e1675886e87dd2\` (\`idTypeRequestId\`), UNIQUE INDEX \`REL_e406cc1ba2f4f628497980a2a9\` (\`fmStatusRequestId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_client\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`last_name\` varchar(255) NOT NULL, \`id_roles\` int NOT NULL DEFAULT '1', \`password\` varchar(255) NOT NULL, \`ident_num\` varchar(255) NOT NULL, \`email\` varchar(255) NOT NULL, \`idIdentTypeId\` int NULL, UNIQUE INDEX \`IDX_778beb473589f56fd8ab17501a\` (\`idIdentTypeId\`, \`ident_num\`), UNIQUE INDEX \`IDX_2b426d3e17a73aa07179aeb223\` (\`email\`), UNIQUE INDEX \`REL_2fcf92bbdd503689cdb184fdba\` (\`idIdentTypeId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_ciudad\` (\`id\` int NOT NULL AUTO_INCREMENT, \`ciudad\` varchar(255) NOT NULL, \`capital\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`idEstadoId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_estado\` (\`id\` int NOT NULL AUTO_INCREMENT, \`estado\` varchar(255) NOT NULL, \`iso_3166\` int NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_parroquia\` (\`id\` int NOT NULL AUTO_INCREMENT, \`parroquia\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`idMunicipioId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_municipio\` (\`id\` int NOT NULL AUTO_INCREMENT, \`municipio\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`idEstadoId\` int NULL, UNIQUE INDEX \`REL_c2952f0ade0c768923bfcd091e\` (\`idEstadoId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_cod_postal\` (\`id\` int NOT NULL AUTO_INCREMENT, \`id_parroquia\` int NOT NULL, \`cod\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_location\` (\`id\` int NOT NULL AUTO_INCREMENT, \`sector\` varchar(255) NOT NULL, \`calle\` varchar(255) NOT NULL, \`local\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`idEstadoId\` int NULL, \`idMunicipioId\` int NULL, \`idCiudadId\` int NULL, \`idParroquiaId\` int NULL, \`idCodPostalId\` int NULL, UNIQUE INDEX \`REL_7faad64c4d276d229d45585e99\` (\`idEstadoId\`), UNIQUE INDEX \`REL_e68b330dedc0ef489fa8b4d423\` (\`idMunicipioId\`), UNIQUE INDEX \`REL_77a478bbe486ef168042ef7709\` (\`idCiudadId\`), UNIQUE INDEX \`REL_681edb0782ea058000073db6f4\` (\`idParroquiaId\`), UNIQUE INDEX \`REL_1958317995d7b21b3174f67f89\` (\`idCodPostalId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_dir_post\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`idLocationId\` int NULL, \`idCommerceId\` int NULL, UNIQUE INDEX \`REL_91fc4ff405576c467174ba9948\` (\`idLocationId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_commerce\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`id_ident_type\` int NOT NULL, \`nro_ident\` varchar(255) NOT NULL, \`special_contributor\` int NOT NULL DEFAULT '0', \`id_location\` int NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`idActivityId\` int NULL, \`idAciId\` int NULL, \`idClientId\` int NULL, UNIQUE INDEX \`REL_196bd8fe75da538dc9d9443566\` (\`idActivityId\`), UNIQUE INDEX \`REL_8531fcd1168b00dc828cd075aa\` (\`idAciId\`), UNIQUE INDEX \`REL_d15fa48b2e2917bbad5ca93f0b\` (\`idClientId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_bank_commerce\` (\`id\` int NOT NULL AUTO_INCREMENT, \`bank_account_num\` int NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`idCommerceId\` int NULL, \`idBankId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_photo\` (\`id\` int NOT NULL AUTO_INCREMENT, \`path\` varchar(255) NOT NULL, \`link\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_worker_id_roles_fm_roles\` (\`fmWorkerId\` int NOT NULL, \`fmRolesId\` int NOT NULL, INDEX \`IDX_b7a9522a06e7bb726aae971474\` (\`fmWorkerId\`), INDEX \`IDX_e76591268bcc2449c6dd2f8eb3\` (\`fmRolesId\`), PRIMARY KEY (\`fmWorkerId\`, \`fmRolesId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_worker_id_depart_fm_department\` (\`fmWorkerId\` int NOT NULL, \`fmDepartmentId\` int NOT NULL, INDEX \`IDX_e2077c5c12d933e07a0e9d4eb1\` (\`fmWorkerId\`), INDEX \`IDX_51b234013c18f576736031ce5a\` (\`fmDepartmentId\`), PRIMARY KEY (\`fmWorkerId\`, \`fmDepartmentId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_client_id_roles_fm_roles\` (\`fmClientId\` int NOT NULL, \`fmRolesId\` int NOT NULL, INDEX \`IDX_867101050576ea82b6410de17e\` (\`fmClientId\`), INDEX \`IDX_5a9520d79b89237a7fbe8e5762\` (\`fmRolesId\`), PRIMARY KEY (\`fmClientId\`, \`fmRolesId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_worker\` ADD CONSTRAINT \`FK_65a70eeb0fb74c503ed15f10647\` FOREIGN KEY (\`idIdentTypeId\`) REFERENCES \`1000pagosdev\`.\`fm_ident_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_phone\` ADD CONSTRAINT \`FK_c6e07f1585b1805268c9c6584a5\` FOREIGN KEY (\`idClientId\`) REFERENCES \`1000pagosdev\`.\`fm_client\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_6c23e4e82323cd84ea108afb6e7\` FOREIGN KEY (\`idPaymentMethodId\`) REFERENCES \`1000pagosdev\`.\`fm_payment_method\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_1134cd317f45c6a39458764451b\` FOREIGN KEY (\`idClientId\`) REFERENCES \`1000pagosdev\`.\`fm_client\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_4634fa27193bcbbe0e27d909385\` FOREIGN KEY (\`idCommerceId\`) REFERENCES \`1000pagosdev\`.\`fm_commerce\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_38f1e43facd2e1675886e87dd21\` FOREIGN KEY (\`idTypeRequestId\`) REFERENCES \`1000pagosdev\`.\`fm_type_request\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_e406cc1ba2f4f628497980a2a91\` FOREIGN KEY (\`fmStatusRequestId\`) REFERENCES \`1000pagosdev\`.\`fm_status_request\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_client\` ADD CONSTRAINT \`FK_2fcf92bbdd503689cdb184fdba2\` FOREIGN KEY (\`idIdentTypeId\`) REFERENCES \`1000pagosdev\`.\`fm_ident_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_ciudad\` ADD CONSTRAINT \`FK_06b45182e630a7a33123d77b6c6\` FOREIGN KEY (\`idEstadoId\`) REFERENCES \`1000pagosdev\`.\`fm_estado\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_parroquia\` ADD CONSTRAINT \`FK_9f3024408c0cb02a72e0898be67\` FOREIGN KEY (\`idMunicipioId\`) REFERENCES \`1000pagosdev\`.\`fm_municipio\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_municipio\` ADD CONSTRAINT \`FK_c2952f0ade0c768923bfcd091e1\` FOREIGN KEY (\`idEstadoId\`) REFERENCES \`1000pagosdev\`.\`fm_estado\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` ADD CONSTRAINT \`FK_7faad64c4d276d229d45585e99c\` FOREIGN KEY (\`idEstadoId\`) REFERENCES \`1000pagosdev\`.\`fm_estado\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` ADD CONSTRAINT \`FK_e68b330dedc0ef489fa8b4d4235\` FOREIGN KEY (\`idMunicipioId\`) REFERENCES \`1000pagosdev\`.\`fm_municipio\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` ADD CONSTRAINT \`FK_77a478bbe486ef168042ef77099\` FOREIGN KEY (\`idCiudadId\`) REFERENCES \`1000pagosdev\`.\`fm_ciudad\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` ADD CONSTRAINT \`FK_681edb0782ea058000073db6f41\` FOREIGN KEY (\`idParroquiaId\`) REFERENCES \`1000pagosdev\`.\`fm_parroquia\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` ADD CONSTRAINT \`FK_1958317995d7b21b3174f67f89f\` FOREIGN KEY (\`idCodPostalId\`) REFERENCES \`1000pagosdev\`.\`fm_cod_postal\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_dir_post\` ADD CONSTRAINT \`FK_91fc4ff405576c467174ba99488\` FOREIGN KEY (\`idLocationId\`) REFERENCES \`1000pagosdev\`.\`fm_location\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_dir_post\` ADD CONSTRAINT \`FK_e1db58f255fe5ca787974f4b023\` FOREIGN KEY (\`idCommerceId\`) REFERENCES \`1000pagosdev\`.\`fm_commerce\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` ADD CONSTRAINT \`FK_196bd8fe75da538dc9d94435666\` FOREIGN KEY (\`idActivityId\`) REFERENCES \`1000pagosdev\`.\`fm_activity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` ADD CONSTRAINT \`FK_8531fcd1168b00dc828cd075aac\` FOREIGN KEY (\`idAciId\`) REFERENCES \`1000pagosdev\`.\`fm_worker\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` ADD CONSTRAINT \`FK_d15fa48b2e2917bbad5ca93f0b9\` FOREIGN KEY (\`idClientId\`) REFERENCES \`1000pagosdev\`.\`fm_client\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_bank_commerce\` ADD CONSTRAINT \`FK_4fdb498852192b9992039cf9dc8\` FOREIGN KEY (\`idCommerceId\`) REFERENCES \`1000pagosdev\`.\`fm_commerce\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_bank_commerce\` ADD CONSTRAINT \`FK_7aca6edbc077a370a90dde3a3da\` FOREIGN KEY (\`idBankId\`) REFERENCES \`1000pagosdev\`.\`fm_bank\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_worker_id_roles_fm_roles\` ADD CONSTRAINT \`FK_b7a9522a06e7bb726aae9714748\` FOREIGN KEY (\`fmWorkerId\`) REFERENCES \`1000pagosdev\`.\`fm_worker\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_worker_id_roles_fm_roles\` ADD CONSTRAINT \`FK_e76591268bcc2449c6dd2f8eb38\` FOREIGN KEY (\`fmRolesId\`) REFERENCES \`1000pagosdev\`.\`fm_roles\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_worker_id_depart_fm_department\` ADD CONSTRAINT \`FK_e2077c5c12d933e07a0e9d4eb12\` FOREIGN KEY (\`fmWorkerId\`) REFERENCES \`1000pagosdev\`.\`fm_worker\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_worker_id_depart_fm_department\` ADD CONSTRAINT \`FK_51b234013c18f576736031ce5a6\` FOREIGN KEY (\`fmDepartmentId\`) REFERENCES \`1000pagosdev\`.\`fm_department\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_client_id_roles_fm_roles\` ADD CONSTRAINT \`FK_867101050576ea82b6410de17ed\` FOREIGN KEY (\`fmClientId\`) REFERENCES \`1000pagosdev\`.\`fm_client\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_client_id_roles_fm_roles\` ADD CONSTRAINT \`FK_5a9520d79b89237a7fbe8e5762e\` FOREIGN KEY (\`fmRolesId\`) REFERENCES \`1000pagosdev\`.\`fm_roles\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_client_id_roles_fm_roles\` DROP FOREIGN KEY \`FK_5a9520d79b89237a7fbe8e5762e\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_client_id_roles_fm_roles\` DROP FOREIGN KEY \`FK_867101050576ea82b6410de17ed\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_worker_id_depart_fm_department\` DROP FOREIGN KEY \`FK_51b234013c18f576736031ce5a6\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_worker_id_depart_fm_department\` DROP FOREIGN KEY \`FK_e2077c5c12d933e07a0e9d4eb12\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_worker_id_roles_fm_roles\` DROP FOREIGN KEY \`FK_e76591268bcc2449c6dd2f8eb38\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_worker_id_roles_fm_roles\` DROP FOREIGN KEY \`FK_b7a9522a06e7bb726aae9714748\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_bank_commerce\` DROP FOREIGN KEY \`FK_7aca6edbc077a370a90dde3a3da\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_bank_commerce\` DROP FOREIGN KEY \`FK_4fdb498852192b9992039cf9dc8\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` DROP FOREIGN KEY \`FK_d15fa48b2e2917bbad5ca93f0b9\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` DROP FOREIGN KEY \`FK_8531fcd1168b00dc828cd075aac\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` DROP FOREIGN KEY \`FK_196bd8fe75da538dc9d94435666\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_dir_post\` DROP FOREIGN KEY \`FK_e1db58f255fe5ca787974f4b023\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_dir_post\` DROP FOREIGN KEY \`FK_91fc4ff405576c467174ba99488\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` DROP FOREIGN KEY \`FK_1958317995d7b21b3174f67f89f\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` DROP FOREIGN KEY \`FK_681edb0782ea058000073db6f41\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` DROP FOREIGN KEY \`FK_77a478bbe486ef168042ef77099\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` DROP FOREIGN KEY \`FK_e68b330dedc0ef489fa8b4d4235\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` DROP FOREIGN KEY \`FK_7faad64c4d276d229d45585e99c\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_municipio\` DROP FOREIGN KEY \`FK_c2952f0ade0c768923bfcd091e1\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_parroquia\` DROP FOREIGN KEY \`FK_9f3024408c0cb02a72e0898be67\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_ciudad\` DROP FOREIGN KEY \`FK_06b45182e630a7a33123d77b6c6\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_client\` DROP FOREIGN KEY \`FK_2fcf92bbdd503689cdb184fdba2\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_e406cc1ba2f4f628497980a2a91\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_38f1e43facd2e1675886e87dd21\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_4634fa27193bcbbe0e27d909385\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_1134cd317f45c6a39458764451b\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_6c23e4e82323cd84ea108afb6e7\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_phone\` DROP FOREIGN KEY \`FK_c6e07f1585b1805268c9c6584a5\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_worker\` DROP FOREIGN KEY \`FK_65a70eeb0fb74c503ed15f10647\``);
        await queryRunner.query(`DROP INDEX \`IDX_5a9520d79b89237a7fbe8e5762\` ON \`1000pagosdev\`.\`fm_client_id_roles_fm_roles\``);
        await queryRunner.query(`DROP INDEX \`IDX_867101050576ea82b6410de17e\` ON \`1000pagosdev\`.\`fm_client_id_roles_fm_roles\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_client_id_roles_fm_roles\``);
        await queryRunner.query(`DROP INDEX \`IDX_51b234013c18f576736031ce5a\` ON \`1000pagosdev\`.\`fm_worker_id_depart_fm_department\``);
        await queryRunner.query(`DROP INDEX \`IDX_e2077c5c12d933e07a0e9d4eb1\` ON \`1000pagosdev\`.\`fm_worker_id_depart_fm_department\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_worker_id_depart_fm_department\``);
        await queryRunner.query(`DROP INDEX \`IDX_e76591268bcc2449c6dd2f8eb3\` ON \`1000pagosdev\`.\`fm_worker_id_roles_fm_roles\``);
        await queryRunner.query(`DROP INDEX \`IDX_b7a9522a06e7bb726aae971474\` ON \`1000pagosdev\`.\`fm_worker_id_roles_fm_roles\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_worker_id_roles_fm_roles\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_photo\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_bank_commerce\``);
        await queryRunner.query(`DROP INDEX \`REL_d15fa48b2e2917bbad5ca93f0b\` ON \`1000pagosdev\`.\`fm_commerce\``);
        await queryRunner.query(`DROP INDEX \`REL_8531fcd1168b00dc828cd075aa\` ON \`1000pagosdev\`.\`fm_commerce\``);
        await queryRunner.query(`DROP INDEX \`REL_196bd8fe75da538dc9d9443566\` ON \`1000pagosdev\`.\`fm_commerce\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_commerce\``);
        await queryRunner.query(`DROP INDEX \`REL_91fc4ff405576c467174ba9948\` ON \`1000pagosdev\`.\`fm_dir_post\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_dir_post\``);
        await queryRunner.query(`DROP INDEX \`REL_1958317995d7b21b3174f67f89\` ON \`1000pagosdev\`.\`fm_location\``);
        await queryRunner.query(`DROP INDEX \`REL_681edb0782ea058000073db6f4\` ON \`1000pagosdev\`.\`fm_location\``);
        await queryRunner.query(`DROP INDEX \`REL_77a478bbe486ef168042ef7709\` ON \`1000pagosdev\`.\`fm_location\``);
        await queryRunner.query(`DROP INDEX \`REL_e68b330dedc0ef489fa8b4d423\` ON \`1000pagosdev\`.\`fm_location\``);
        await queryRunner.query(`DROP INDEX \`REL_7faad64c4d276d229d45585e99\` ON \`1000pagosdev\`.\`fm_location\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_location\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_cod_postal\``);
        await queryRunner.query(`DROP INDEX \`REL_c2952f0ade0c768923bfcd091e\` ON \`1000pagosdev\`.\`fm_municipio\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_municipio\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_parroquia\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_estado\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_ciudad\``);
        await queryRunner.query(`DROP INDEX \`REL_2fcf92bbdd503689cdb184fdba\` ON \`1000pagosdev\`.\`fm_client\``);
        await queryRunner.query(`DROP INDEX \`IDX_2b426d3e17a73aa07179aeb223\` ON \`1000pagosdev\`.\`fm_client\``);
        await queryRunner.query(`DROP INDEX \`IDX_778beb473589f56fd8ab17501a\` ON \`1000pagosdev\`.\`fm_client\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_client\``);
        await queryRunner.query(`DROP INDEX \`REL_e406cc1ba2f4f628497980a2a9\` ON \`1000pagosdev\`.\`fm_request\``);
        await queryRunner.query(`DROP INDEX \`REL_38f1e43facd2e1675886e87dd2\` ON \`1000pagosdev\`.\`fm_request\``);
        await queryRunner.query(`DROP INDEX \`REL_6c23e4e82323cd84ea108afb6e\` ON \`1000pagosdev\`.\`fm_request\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_request\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_status_request\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_type_request\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_payment_method\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_phone\``);
        await queryRunner.query(`DROP INDEX \`REL_65a70eeb0fb74c503ed15f1064\` ON \`1000pagosdev\`.\`fm_worker\``);
        await queryRunner.query(`DROP INDEX \`IDX_35eb1f25e7bf89140a2c986b07\` ON \`1000pagosdev\`.\`fm_worker\``);
        await queryRunner.query(`DROP INDEX \`IDX_116ab774592bca9d98010aa4c3\` ON \`1000pagosdev\`.\`fm_worker\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_worker\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_department\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_roles\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_ident_type\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_bank\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_activity\``);
    }

}
