import {MigrationInterface, QueryRunner} from "typeorm";

export class initDB1630012096342 implements MigrationInterface {
    name = 'initDB1630012096342'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_phone\` DROP FOREIGN KEY \`FK_c6e07f1585b1805268c9c6584a5\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_phone\` CHANGE \`idClientId\` \`idClientId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_af880b2a93f79cc4377ab8c7ac7\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_1134cd317f45c6a39458764451b\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_4634fa27193bcbbe0e27d909385\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_38f1e43facd2e1675886e87dd21\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_e406cc1ba2f4f628497980a2a91\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`idWayPayId\` \`idWayPayId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`idClientId\` \`idClientId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`idCommerceId\` \`idCommerceId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`idTypeRequestId\` \`idTypeRequestId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`fmStatusRequestId\` \`fmStatusRequestId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_client\` DROP FOREIGN KEY \`FK_2fcf92bbdd503689cdb184fdba2\``);
        await queryRunner.query(`DROP INDEX \`IDX_778beb473589f56fd8ab17501a\` ON \`1000pagosdev\`.\`fm_client\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_client\` CHANGE \`idIdentTypeId\` \`idIdentTypeId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_ciudad\` DROP FOREIGN KEY \`FK_06b45182e630a7a33123d77b6c6\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_ciudad\` CHANGE \`idEstadoId\` \`idEstadoId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_parroquia\` DROP FOREIGN KEY \`FK_9f3024408c0cb02a72e0898be67\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_parroquia\` CHANGE \`idMunicipioId\` \`idMunicipioId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_municipio\` DROP FOREIGN KEY \`FK_c2952f0ade0c768923bfcd091e1\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_municipio\` CHANGE \`idEstadoId\` \`idEstadoId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` DROP FOREIGN KEY \`FK_7faad64c4d276d229d45585e99c\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` DROP FOREIGN KEY \`FK_e68b330dedc0ef489fa8b4d4235\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` DROP FOREIGN KEY \`FK_77a478bbe486ef168042ef77099\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` DROP FOREIGN KEY \`FK_681edb0782ea058000073db6f41\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` DROP FOREIGN KEY \`FK_1958317995d7b21b3174f67f89f\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` CHANGE \`idEstadoId\` \`idEstadoId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` CHANGE \`idMunicipioId\` \`idMunicipioId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` CHANGE \`idCiudadId\` \`idCiudadId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` CHANGE \`idParroquiaId\` \`idParroquiaId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` CHANGE \`idCodPostalId\` \`idCodPostalId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_dir_post\` DROP FOREIGN KEY \`FK_91fc4ff405576c467174ba99488\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_dir_post\` DROP FOREIGN KEY \`FK_e1db58f255fe5ca787974f4b023\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_dir_post\` CHANGE \`idLocationId\` \`idLocationId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_dir_post\` CHANGE \`idCommerceId\` \`idCommerceId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` DROP FOREIGN KEY \`FK_196bd8fe75da538dc9d94435666\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` DROP FOREIGN KEY \`FK_8531fcd1168b00dc828cd075aac\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` DROP FOREIGN KEY \`FK_d15fa48b2e2917bbad5ca93f0b9\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` CHANGE \`idActivityId\` \`idActivityId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` CHANGE \`idAciId\` \`idAciId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` CHANGE \`idClientId\` \`idClientId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_bank_commerce\` DROP FOREIGN KEY \`FK_4fdb498852192b9992039cf9dc8\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_bank_commerce\` DROP FOREIGN KEY \`FK_7aca6edbc077a370a90dde3a3da\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_bank_commerce\` CHANGE \`idCommerceId\` \`idCommerceId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_bank_commerce\` CHANGE \`idBankId\` \`idBankId\` int NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_778beb473589f56fd8ab17501a\` ON \`1000pagosdev\`.\`fm_client\` (\`idIdentTypeId\`, \`ident_num\`)`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_phone\` ADD CONSTRAINT \`FK_c6e07f1585b1805268c9c6584a5\` FOREIGN KEY (\`idClientId\`) REFERENCES \`1000pagosdev\`.\`fm_client\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_af880b2a93f79cc4377ab8c7ac7\` FOREIGN KEY (\`idWayPayId\`) REFERENCES \`1000pagosdev\`.\`fm_way_pay\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_1134cd317f45c6a39458764451b\` FOREIGN KEY (\`idClientId\`) REFERENCES \`1000pagosdev\`.\`fm_client\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_4634fa27193bcbbe0e27d909385\` FOREIGN KEY (\`idCommerceId\`) REFERENCES \`1000pagosdev\`.\`fm_commerce\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_38f1e43facd2e1675886e87dd21\` FOREIGN KEY (\`idTypeRequestId\`) REFERENCES \`1000pagosdev\`.\`fm_type_request\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_e406cc1ba2f4f628497980a2a91\` FOREIGN KEY (\`fmStatusRequestId\`) REFERENCES \`1000pagosdev\`.\`fm_status_request\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_client\` ADD CONSTRAINT \`FK_2fcf92bbdd503689cdb184fdba2\` FOREIGN KEY (\`idIdentTypeId\`) REFERENCES \`1000pagosdev\`.\`fm_ident_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_ciudad\` ADD CONSTRAINT \`FK_06b45182e630a7a33123d77b6c6\` FOREIGN KEY (\`idEstadoId\`) REFERENCES \`1000pagosdev\`.\`fm_estado\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_parroquia\` ADD CONSTRAINT \`FK_9f3024408c0cb02a72e0898be67\` FOREIGN KEY (\`idMunicipioId\`) REFERENCES \`1000pagosdev\`.\`fm_municipio\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_municipio\` ADD CONSTRAINT \`FK_c2952f0ade0c768923bfcd091e1\` FOREIGN KEY (\`idEstadoId\`) REFERENCES \`1000pagosdev\`.\`fm_estado\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` ADD CONSTRAINT \`FK_7faad64c4d276d229d45585e99c\` FOREIGN KEY (\`idEstadoId\`) REFERENCES \`1000pagosdev\`.\`fm_estado\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` ADD CONSTRAINT \`FK_e68b330dedc0ef489fa8b4d4235\` FOREIGN KEY (\`idMunicipioId\`) REFERENCES \`1000pagosdev\`.\`fm_municipio\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` ADD CONSTRAINT \`FK_77a478bbe486ef168042ef77099\` FOREIGN KEY (\`idCiudadId\`) REFERENCES \`1000pagosdev\`.\`fm_ciudad\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` ADD CONSTRAINT \`FK_681edb0782ea058000073db6f41\` FOREIGN KEY (\`idParroquiaId\`) REFERENCES \`1000pagosdev\`.\`fm_parroquia\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` ADD CONSTRAINT \`FK_1958317995d7b21b3174f67f89f\` FOREIGN KEY (\`idCodPostalId\`) REFERENCES \`1000pagosdev\`.\`fm_cod_postal\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_dir_post\` ADD CONSTRAINT \`FK_91fc4ff405576c467174ba99488\` FOREIGN KEY (\`idLocationId\`) REFERENCES \`1000pagosdev\`.\`fm_location\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_dir_post\` ADD CONSTRAINT \`FK_e1db58f255fe5ca787974f4b023\` FOREIGN KEY (\`idCommerceId\`) REFERENCES \`1000pagosdev\`.\`fm_commerce\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` ADD CONSTRAINT \`FK_196bd8fe75da538dc9d94435666\` FOREIGN KEY (\`idActivityId\`) REFERENCES \`1000pagosdev\`.\`fm_activity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` ADD CONSTRAINT \`FK_8531fcd1168b00dc828cd075aac\` FOREIGN KEY (\`idAciId\`) REFERENCES \`1000pagosdev\`.\`fm_worker\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` ADD CONSTRAINT \`FK_d15fa48b2e2917bbad5ca93f0b9\` FOREIGN KEY (\`idClientId\`) REFERENCES \`1000pagosdev\`.\`fm_client\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_bank_commerce\` ADD CONSTRAINT \`FK_4fdb498852192b9992039cf9dc8\` FOREIGN KEY (\`idCommerceId\`) REFERENCES \`1000pagosdev\`.\`fm_commerce\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_bank_commerce\` ADD CONSTRAINT \`FK_7aca6edbc077a370a90dde3a3da\` FOREIGN KEY (\`idBankId\`) REFERENCES \`1000pagosdev\`.\`fm_bank\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_bank_commerce\` DROP FOREIGN KEY \`FK_7aca6edbc077a370a90dde3a3da\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_bank_commerce\` DROP FOREIGN KEY \`FK_4fdb498852192b9992039cf9dc8\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` DROP FOREIGN KEY \`FK_d15fa48b2e2917bbad5ca93f0b9\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` DROP FOREIGN KEY \`FK_8531fcd1168b00dc828cd075aac\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` DROP FOREIGN KEY \`FK_196bd8fe75da538dc9d94435666\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_dir_post\` DROP FOREIGN KEY \`FK_e1db58f255fe5ca787974f4b023\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_dir_post\` DROP FOREIGN KEY \`FK_91fc4ff405576c467174ba99488\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` DROP FOREIGN KEY \`FK_1958317995d7b21b3174f67f89f\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` DROP FOREIGN KEY \`FK_681edb0782ea058000073db6f41\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` DROP FOREIGN KEY \`FK_77a478bbe486ef168042ef77099\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` DROP FOREIGN KEY \`FK_e68b330dedc0ef489fa8b4d4235\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` DROP FOREIGN KEY \`FK_7faad64c4d276d229d45585e99c\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_municipio\` DROP FOREIGN KEY \`FK_c2952f0ade0c768923bfcd091e1\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_parroquia\` DROP FOREIGN KEY \`FK_9f3024408c0cb02a72e0898be67\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_ciudad\` DROP FOREIGN KEY \`FK_06b45182e630a7a33123d77b6c6\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_client\` DROP FOREIGN KEY \`FK_2fcf92bbdd503689cdb184fdba2\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_e406cc1ba2f4f628497980a2a91\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_38f1e43facd2e1675886e87dd21\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_4634fa27193bcbbe0e27d909385\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_1134cd317f45c6a39458764451b\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_af880b2a93f79cc4377ab8c7ac7\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_phone\` DROP FOREIGN KEY \`FK_c6e07f1585b1805268c9c6584a5\``);
        await queryRunner.query(`DROP INDEX \`IDX_778beb473589f56fd8ab17501a\` ON \`1000pagosdev\`.\`fm_client\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_bank_commerce\` CHANGE \`idBankId\` \`idBankId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_bank_commerce\` CHANGE \`idCommerceId\` \`idCommerceId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_bank_commerce\` ADD CONSTRAINT \`FK_7aca6edbc077a370a90dde3a3da\` FOREIGN KEY (\`idBankId\`) REFERENCES \`1000pagosdev\`.\`fm_bank\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_bank_commerce\` ADD CONSTRAINT \`FK_4fdb498852192b9992039cf9dc8\` FOREIGN KEY (\`idCommerceId\`) REFERENCES \`1000pagosdev\`.\`fm_commerce\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` CHANGE \`idClientId\` \`idClientId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` CHANGE \`idAciId\` \`idAciId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` CHANGE \`idActivityId\` \`idActivityId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` ADD CONSTRAINT \`FK_d15fa48b2e2917bbad5ca93f0b9\` FOREIGN KEY (\`idClientId\`) REFERENCES \`1000pagosdev\`.\`fm_client\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` ADD CONSTRAINT \`FK_8531fcd1168b00dc828cd075aac\` FOREIGN KEY (\`idAciId\`) REFERENCES \`1000pagosdev\`.\`fm_worker\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` ADD CONSTRAINT \`FK_196bd8fe75da538dc9d94435666\` FOREIGN KEY (\`idActivityId\`) REFERENCES \`1000pagosdev\`.\`fm_activity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_dir_post\` CHANGE \`idCommerceId\` \`idCommerceId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_dir_post\` CHANGE \`idLocationId\` \`idLocationId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_dir_post\` ADD CONSTRAINT \`FK_e1db58f255fe5ca787974f4b023\` FOREIGN KEY (\`idCommerceId\`) REFERENCES \`1000pagosdev\`.\`fm_commerce\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_dir_post\` ADD CONSTRAINT \`FK_91fc4ff405576c467174ba99488\` FOREIGN KEY (\`idLocationId\`) REFERENCES \`1000pagosdev\`.\`fm_location\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` CHANGE \`idCodPostalId\` \`idCodPostalId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` CHANGE \`idParroquiaId\` \`idParroquiaId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` CHANGE \`idCiudadId\` \`idCiudadId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` CHANGE \`idMunicipioId\` \`idMunicipioId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` CHANGE \`idEstadoId\` \`idEstadoId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` ADD CONSTRAINT \`FK_1958317995d7b21b3174f67f89f\` FOREIGN KEY (\`idCodPostalId\`) REFERENCES \`1000pagosdev\`.\`fm_cod_postal\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` ADD CONSTRAINT \`FK_681edb0782ea058000073db6f41\` FOREIGN KEY (\`idParroquiaId\`) REFERENCES \`1000pagosdev\`.\`fm_parroquia\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` ADD CONSTRAINT \`FK_77a478bbe486ef168042ef77099\` FOREIGN KEY (\`idCiudadId\`) REFERENCES \`1000pagosdev\`.\`fm_ciudad\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` ADD CONSTRAINT \`FK_e68b330dedc0ef489fa8b4d4235\` FOREIGN KEY (\`idMunicipioId\`) REFERENCES \`1000pagosdev\`.\`fm_municipio\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` ADD CONSTRAINT \`FK_7faad64c4d276d229d45585e99c\` FOREIGN KEY (\`idEstadoId\`) REFERENCES \`1000pagosdev\`.\`fm_estado\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_municipio\` CHANGE \`idEstadoId\` \`idEstadoId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_municipio\` ADD CONSTRAINT \`FK_c2952f0ade0c768923bfcd091e1\` FOREIGN KEY (\`idEstadoId\`) REFERENCES \`1000pagosdev\`.\`fm_estado\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_parroquia\` CHANGE \`idMunicipioId\` \`idMunicipioId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_parroquia\` ADD CONSTRAINT \`FK_9f3024408c0cb02a72e0898be67\` FOREIGN KEY (\`idMunicipioId\`) REFERENCES \`1000pagosdev\`.\`fm_municipio\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_ciudad\` CHANGE \`idEstadoId\` \`idEstadoId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_ciudad\` ADD CONSTRAINT \`FK_06b45182e630a7a33123d77b6c6\` FOREIGN KEY (\`idEstadoId\`) REFERENCES \`1000pagosdev\`.\`fm_estado\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_client\` CHANGE \`idIdentTypeId\` \`idIdentTypeId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_778beb473589f56fd8ab17501a\` ON \`1000pagosdev\`.\`fm_client\` (\`idIdentTypeId\`, \`ident_num\`)`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_client\` ADD CONSTRAINT \`FK_2fcf92bbdd503689cdb184fdba2\` FOREIGN KEY (\`idIdentTypeId\`) REFERENCES \`1000pagosdev\`.\`fm_ident_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`fmStatusRequestId\` \`fmStatusRequestId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`idTypeRequestId\` \`idTypeRequestId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`idCommerceId\` \`idCommerceId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`idClientId\` \`idClientId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` CHANGE \`idWayPayId\` \`idWayPayId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_e406cc1ba2f4f628497980a2a91\` FOREIGN KEY (\`fmStatusRequestId\`) REFERENCES \`1000pagosdev\`.\`fm_status_request\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_38f1e43facd2e1675886e87dd21\` FOREIGN KEY (\`idTypeRequestId\`) REFERENCES \`1000pagosdev\`.\`fm_type_request\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_4634fa27193bcbbe0e27d909385\` FOREIGN KEY (\`idCommerceId\`) REFERENCES \`1000pagosdev\`.\`fm_commerce\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_1134cd317f45c6a39458764451b\` FOREIGN KEY (\`idClientId\`) REFERENCES \`1000pagosdev\`.\`fm_client\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_af880b2a93f79cc4377ab8c7ac7\` FOREIGN KEY (\`idWayPayId\`) REFERENCES \`1000pagosdev\`.\`fm_way_pay\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_phone\` CHANGE \`idClientId\` \`idClientId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_phone\` ADD CONSTRAINT \`FK_c6e07f1585b1805268c9c6584a5\` FOREIGN KEY (\`idClientId\`) REFERENCES \`1000pagosdev\`.\`fm_client\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
