import {MigrationInterface, QueryRunner} from "typeorm";

export class initDB1632247890738 implements MigrationInterface {
    name = 'initDB1632247890738'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_activity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_ident_type\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_phone\` (\`id\` int NOT NULL AUTO_INCREMENT, \`phone\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`id_client\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_payment_method\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_type_request\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_status_request\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_photo\` (\`id\` int NOT NULL AUTO_INCREMENT, \`path\` varchar(255) NOT NULL, \`link\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, \`descript\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_ciudad\` (\`id\` int NOT NULL AUTO_INCREMENT, \`ciudad\` varchar(255) NOT NULL, \`capital\` tinyint NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`id_estado\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_parroquia\` (\`id\` int NOT NULL AUTO_INCREMENT, \`parroquia\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`id_municipio\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_municipio\` (\`id\` int NOT NULL AUTO_INCREMENT, \`municipio\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`id_estado\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_estado\` (\`id\` int NOT NULL AUTO_INCREMENT, \`estado\` varchar(255) NOT NULL, \`iso_3166\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_location\` (\`id\` int NOT NULL AUTO_INCREMENT, \`sector\` varchar(255) NOT NULL, \`calle\` varchar(255) NOT NULL, \`local\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`id_estado\` int NULL, \`id_municipio\` int NULL, \`id_ciudad\` int NULL, \`id_parroquia\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_dir_pos\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`id_location\` int NULL, \`id_commerce\` int NULL, \`id_request\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_request\` (\`id\` int NOT NULL AUTO_INCREMENT, \`number_post\` int NOT NULL, \`bank_account_num\` varchar(255) NOT NULL, \`id_status_request\` int NOT NULL DEFAULT '0', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`rc_constitutive_act\` int NULL, \`rc_property_document\` int NULL, \`rc_service_document\` int NULL, \`rc_special_contributor\` int NULL, \`rc_ref_bank\` int NULL, \`rc_ref_perso\` int NULL, \`rc_account_number\` int NULL, \`rc_rif\` int NULL, \`rc_ident_card\` int NULL, \`id_payment_method\` int NULL, \`id_client\` int NULL, \`id_commerce\` int NULL, \`id_type_request\` int NULL, UNIQUE INDEX \`REL_af1eae98b17fa9e92881cafce3\` (\`rc_constitutive_act\`), UNIQUE INDEX \`REL_5a70c1436abb7fb7bb081bd667\` (\`rc_property_document\`), UNIQUE INDEX \`REL_784d15eaace1537f9f699aff25\` (\`rc_service_document\`), UNIQUE INDEX \`REL_b5772edefef68ff71c6477c970\` (\`rc_special_contributor\`), UNIQUE INDEX \`REL_4f207c9a0e9645910383377f86\` (\`rc_ref_bank\`), UNIQUE INDEX \`REL_ecb3a612691fb1e01af12683e3\` (\`rc_ref_perso\`), UNIQUE INDEX \`REL_4668ebbef8614032e9d58794d4\` (\`rc_account_number\`), UNIQUE INDEX \`REL_395407df85335f0e00430aa387\` (\`rc_rif\`), UNIQUE INDEX \`REL_9dd51a6b0f9bc09cd820b0c807\` (\`rc_ident_card\`), UNIQUE INDEX \`REL_7af3f0d3b144b7d6a72ceac407\` (\`id_payment_method\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_company\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`id_commerce\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_department\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_worker\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`last_name\` varchar(255) NOT NULL, \`password\` varchar(255) NOT NULL, \`ident_num\` varchar(255) NOT NULL, \`email\` varchar(255) NOT NULL, \`block\` int NOT NULL DEFAULT '0', \`phone\` varchar(255) NOT NULL, \`id_ident_type\` int NULL, \`id_company\` int NULL, \`id_department\` int NULL, UNIQUE INDEX \`IDX_7a21b1b04b3df8909ad71d8909\` (\`id_ident_type\`, \`ident_num\`), UNIQUE INDEX \`IDX_35eb1f25e7bf89140a2c986b07\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_roles\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_client\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`last_name\` varchar(255) NOT NULL, \`id_roles\` int NOT NULL DEFAULT '1', \`password\` varchar(255) NOT NULL, \`ident_num\` varchar(255) NOT NULL, \`email\` varchar(255) NOT NULL, \`id_ident_type\` int NULL, UNIQUE INDEX \`IDX_15f756dc2a9a6aefe1751f731f\` (\`id_ident_type\`, \`ident_num\`), UNIQUE INDEX \`IDX_2b426d3e17a73aa07179aeb223\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_bank\` (\`id\` int NOT NULL AUTO_INCREMENT, \`code\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_bank_commerce\` (\`id\` int NOT NULL AUTO_INCREMENT, \`bank_account_num\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`id_commerce\` int NULL, \`id_bank\` int NULL, UNIQUE INDEX \`IDX_97f25df8772b14b2bf67a227e0\` (\`bank_account_num\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_commerce\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`id_ident_type\` int NOT NULL, \`ident_num\` varchar(255) NOT NULL, \`special_contributor\` int NOT NULL DEFAULT '0', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`id_location\` int NULL, \`id_client\` int NULL, UNIQUE INDEX \`REL_e74342f2c030e08992c56df0af\` (\`id_location\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_aci_commerce\` (\`id\` int NOT NULL AUTO_INCREMENT, \`bank_account_num\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`id_commerce\` int NULL, \`id_bank\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_product\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`description\` varchar(255) NOT NULL, \`price\` int NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`id_paym_method\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_worker_roles_fm_roles\` (\`fmWorkerId\` int NOT NULL, \`fmRolesId\` int NOT NULL, INDEX \`IDX_4bed12461b5ec1b54453861715\` (\`fmWorkerId\`), INDEX \`IDX_309b6bc22137cc95e2efd3f16f\` (\`fmRolesId\`), PRIMARY KEY (\`fmWorkerId\`, \`fmRolesId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_client_id_roles_fm_roles\` (\`fmClientId\` int NOT NULL, \`fmRolesId\` int NOT NULL, INDEX \`IDX_867101050576ea82b6410de17e\` (\`fmClientId\`), INDEX \`IDX_5a9520d79b89237a7fbe8e5762\` (\`fmRolesId\`), PRIMARY KEY (\`fmClientId\`, \`fmRolesId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_client_photos_fm_photo\` (\`fmClientId\` int NOT NULL, \`fmPhotoId\` int NOT NULL, INDEX \`IDX_f6c435979c0cb0f36c0694741b\` (\`fmClientId\`), INDEX \`IDX_9d63958d62d8e50a075685c741\` (\`fmPhotoId\`), PRIMARY KEY (\`fmClientId\`, \`fmPhotoId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`1000pagosdev\`.\`fm_commerce_photos_fm_photo\` (\`fmCommerceId\` int NOT NULL, \`fmPhotoId\` int NOT NULL, INDEX \`IDX_7c7ed8c1193d25825291a17646\` (\`fmCommerceId\`), INDEX \`IDX_422cda263f57b299d3c85a40bd\` (\`fmPhotoId\`), PRIMARY KEY (\`fmCommerceId\`, \`fmPhotoId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_phone\` ADD CONSTRAINT \`FK_3796c0f20cddbfce6840776200f\` FOREIGN KEY (\`id_client\`) REFERENCES \`1000pagosdev\`.\`fm_client\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_ciudad\` ADD CONSTRAINT \`FK_41e29c427582948e763288142c1\` FOREIGN KEY (\`id_estado\`) REFERENCES \`1000pagosdev\`.\`fm_estado\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_parroquia\` ADD CONSTRAINT \`FK_4ac1c804b1f8dcfc3b08363151f\` FOREIGN KEY (\`id_municipio\`) REFERENCES \`1000pagosdev\`.\`fm_municipio\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_municipio\` ADD CONSTRAINT \`FK_9210306e682154252390bb45859\` FOREIGN KEY (\`id_estado\`) REFERENCES \`1000pagosdev\`.\`fm_estado\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` ADD CONSTRAINT \`FK_61ea978348ae6a36894bd39de24\` FOREIGN KEY (\`id_estado\`) REFERENCES \`1000pagosdev\`.\`fm_estado\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` ADD CONSTRAINT \`FK_1c57c6523dd537b0ef0a9f5b419\` FOREIGN KEY (\`id_municipio\`) REFERENCES \`1000pagosdev\`.\`fm_municipio\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` ADD CONSTRAINT \`FK_3e940da713ea86a9367f70618d0\` FOREIGN KEY (\`id_ciudad\`) REFERENCES \`1000pagosdev\`.\`fm_ciudad\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` ADD CONSTRAINT \`FK_73174abf588e8edc848e2e3a121\` FOREIGN KEY (\`id_parroquia\`) REFERENCES \`1000pagosdev\`.\`fm_parroquia\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_dir_pos\` ADD CONSTRAINT \`FK_7a14b7e77f8a819735106b016e5\` FOREIGN KEY (\`id_location\`) REFERENCES \`1000pagosdev\`.\`fm_location\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_dir_pos\` ADD CONSTRAINT \`FK_7ef2c34882b3fb18bc366679aa6\` FOREIGN KEY (\`id_commerce\`) REFERENCES \`1000pagosdev\`.\`fm_commerce\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_dir_pos\` ADD CONSTRAINT \`FK_9af2a5b750e303f6a4e5870a443\` FOREIGN KEY (\`id_request\`) REFERENCES \`1000pagosdev\`.\`fm_request\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_af1eae98b17fa9e92881cafce3d\` FOREIGN KEY (\`rc_constitutive_act\`) REFERENCES \`1000pagosdev\`.\`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_5a70c1436abb7fb7bb081bd667e\` FOREIGN KEY (\`rc_property_document\`) REFERENCES \`1000pagosdev\`.\`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_784d15eaace1537f9f699aff258\` FOREIGN KEY (\`rc_service_document\`) REFERENCES \`1000pagosdev\`.\`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_b5772edefef68ff71c6477c9705\` FOREIGN KEY (\`rc_special_contributor\`) REFERENCES \`1000pagosdev\`.\`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_4f207c9a0e9645910383377f86d\` FOREIGN KEY (\`rc_ref_bank\`) REFERENCES \`1000pagosdev\`.\`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_ecb3a612691fb1e01af12683e37\` FOREIGN KEY (\`rc_ref_perso\`) REFERENCES \`1000pagosdev\`.\`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_4668ebbef8614032e9d58794d46\` FOREIGN KEY (\`rc_account_number\`) REFERENCES \`1000pagosdev\`.\`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_395407df85335f0e00430aa3876\` FOREIGN KEY (\`rc_rif\`) REFERENCES \`1000pagosdev\`.\`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_9dd51a6b0f9bc09cd820b0c8076\` FOREIGN KEY (\`rc_ident_card\`) REFERENCES \`1000pagosdev\`.\`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_7af3f0d3b144b7d6a72ceac4073\` FOREIGN KEY (\`id_payment_method\`) REFERENCES \`1000pagosdev\`.\`fm_payment_method\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_bd495da93173bc09fe6d62b98b5\` FOREIGN KEY (\`id_client\`) REFERENCES \`1000pagosdev\`.\`fm_client\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_96c58e4419abc60056da31ef769\` FOREIGN KEY (\`id_commerce\`) REFERENCES \`1000pagosdev\`.\`fm_commerce\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_8e6a76c31cf8fb8ef74f4823e10\` FOREIGN KEY (\`id_type_request\`) REFERENCES \`1000pagosdev\`.\`fm_type_request\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` ADD CONSTRAINT \`FK_01f14ecde9b1019595b183f3e25\` FOREIGN KEY (\`id_status_request\`) REFERENCES \`1000pagosdev\`.\`fm_status_request\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_company\` ADD CONSTRAINT \`FK_dbee0c02784ebe3f0c0330014b4\` FOREIGN KEY (\`id_commerce\`) REFERENCES \`1000pagosdev\`.\`fm_worker\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_worker\` ADD CONSTRAINT \`FK_e018746d22c55fc0477298963ad\` FOREIGN KEY (\`id_ident_type\`) REFERENCES \`1000pagosdev\`.\`fm_ident_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_worker\` ADD CONSTRAINT \`FK_93ed0b26dab2997d685e1ea0e56\` FOREIGN KEY (\`id_company\`) REFERENCES \`1000pagosdev\`.\`fm_company\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_worker\` ADD CONSTRAINT \`FK_b7651b1e49eddd73c4d3a78c0a3\` FOREIGN KEY (\`id_department\`) REFERENCES \`1000pagosdev\`.\`fm_department\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_client\` ADD CONSTRAINT \`FK_a4d752b12018c7ffc6a64a65307\` FOREIGN KEY (\`id_ident_type\`) REFERENCES \`1000pagosdev\`.\`fm_ident_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_bank_commerce\` ADD CONSTRAINT \`FK_f6a998bb3ed4eb4c244b9baa7f3\` FOREIGN KEY (\`id_commerce\`) REFERENCES \`1000pagosdev\`.\`fm_commerce\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_bank_commerce\` ADD CONSTRAINT \`FK_ac51278339d6ed7a4bcbb5bda7f\` FOREIGN KEY (\`id_bank\`) REFERENCES \`1000pagosdev\`.\`fm_bank\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` ADD CONSTRAINT \`FK_e74342f2c030e08992c56df0af9\` FOREIGN KEY (\`id_location\`) REFERENCES \`1000pagosdev\`.\`fm_location\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` ADD CONSTRAINT \`FK_ae4a2f524f6c29e5d38f265f7ac\` FOREIGN KEY (\`id_client\`) REFERENCES \`1000pagosdev\`.\`fm_client\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_aci_commerce\` ADD CONSTRAINT \`FK_30c2d9c55728a95e712e8373627\` FOREIGN KEY (\`id_commerce\`) REFERENCES \`1000pagosdev\`.\`fm_commerce\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_aci_commerce\` ADD CONSTRAINT \`FK_468916a89469c5b93e8b5d8010e\` FOREIGN KEY (\`id_bank\`) REFERENCES \`1000pagosdev\`.\`fm_worker\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_product\` ADD CONSTRAINT \`FK_cc8feb26b45d579f0f7372aca66\` FOREIGN KEY (\`id_paym_method\`) REFERENCES \`1000pagosdev\`.\`fm_payment_method\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_worker_roles_fm_roles\` ADD CONSTRAINT \`FK_4bed12461b5ec1b54453861715e\` FOREIGN KEY (\`fmWorkerId\`) REFERENCES \`1000pagosdev\`.\`fm_worker\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_worker_roles_fm_roles\` ADD CONSTRAINT \`FK_309b6bc22137cc95e2efd3f16f0\` FOREIGN KEY (\`fmRolesId\`) REFERENCES \`1000pagosdev\`.\`fm_roles\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_client_id_roles_fm_roles\` ADD CONSTRAINT \`FK_867101050576ea82b6410de17ed\` FOREIGN KEY (\`fmClientId\`) REFERENCES \`1000pagosdev\`.\`fm_client\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_client_id_roles_fm_roles\` ADD CONSTRAINT \`FK_5a9520d79b89237a7fbe8e5762e\` FOREIGN KEY (\`fmRolesId\`) REFERENCES \`1000pagosdev\`.\`fm_roles\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_client_photos_fm_photo\` ADD CONSTRAINT \`FK_f6c435979c0cb0f36c0694741b4\` FOREIGN KEY (\`fmClientId\`) REFERENCES \`1000pagosdev\`.\`fm_client\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_client_photos_fm_photo\` ADD CONSTRAINT \`FK_9d63958d62d8e50a075685c7413\` FOREIGN KEY (\`fmPhotoId\`) REFERENCES \`1000pagosdev\`.\`fm_photo\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce_photos_fm_photo\` ADD CONSTRAINT \`FK_7c7ed8c1193d25825291a176466\` FOREIGN KEY (\`fmCommerceId\`) REFERENCES \`1000pagosdev\`.\`fm_commerce\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce_photos_fm_photo\` ADD CONSTRAINT \`FK_422cda263f57b299d3c85a40bd7\` FOREIGN KEY (\`fmPhotoId\`) REFERENCES \`1000pagosdev\`.\`fm_photo\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce_photos_fm_photo\` DROP FOREIGN KEY \`FK_422cda263f57b299d3c85a40bd7\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce_photos_fm_photo\` DROP FOREIGN KEY \`FK_7c7ed8c1193d25825291a176466\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_client_photos_fm_photo\` DROP FOREIGN KEY \`FK_9d63958d62d8e50a075685c7413\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_client_photos_fm_photo\` DROP FOREIGN KEY \`FK_f6c435979c0cb0f36c0694741b4\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_client_id_roles_fm_roles\` DROP FOREIGN KEY \`FK_5a9520d79b89237a7fbe8e5762e\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_client_id_roles_fm_roles\` DROP FOREIGN KEY \`FK_867101050576ea82b6410de17ed\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_worker_roles_fm_roles\` DROP FOREIGN KEY \`FK_309b6bc22137cc95e2efd3f16f0\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_worker_roles_fm_roles\` DROP FOREIGN KEY \`FK_4bed12461b5ec1b54453861715e\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_product\` DROP FOREIGN KEY \`FK_cc8feb26b45d579f0f7372aca66\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_aci_commerce\` DROP FOREIGN KEY \`FK_468916a89469c5b93e8b5d8010e\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_aci_commerce\` DROP FOREIGN KEY \`FK_30c2d9c55728a95e712e8373627\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` DROP FOREIGN KEY \`FK_ae4a2f524f6c29e5d38f265f7ac\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_commerce\` DROP FOREIGN KEY \`FK_e74342f2c030e08992c56df0af9\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_bank_commerce\` DROP FOREIGN KEY \`FK_ac51278339d6ed7a4bcbb5bda7f\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_bank_commerce\` DROP FOREIGN KEY \`FK_f6a998bb3ed4eb4c244b9baa7f3\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_client\` DROP FOREIGN KEY \`FK_a4d752b12018c7ffc6a64a65307\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_worker\` DROP FOREIGN KEY \`FK_b7651b1e49eddd73c4d3a78c0a3\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_worker\` DROP FOREIGN KEY \`FK_93ed0b26dab2997d685e1ea0e56\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_worker\` DROP FOREIGN KEY \`FK_e018746d22c55fc0477298963ad\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_company\` DROP FOREIGN KEY \`FK_dbee0c02784ebe3f0c0330014b4\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_01f14ecde9b1019595b183f3e25\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_8e6a76c31cf8fb8ef74f4823e10\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_96c58e4419abc60056da31ef769\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_bd495da93173bc09fe6d62b98b5\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_7af3f0d3b144b7d6a72ceac4073\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_9dd51a6b0f9bc09cd820b0c8076\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_395407df85335f0e00430aa3876\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_4668ebbef8614032e9d58794d46\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_ecb3a612691fb1e01af12683e37\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_4f207c9a0e9645910383377f86d\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_b5772edefef68ff71c6477c9705\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_784d15eaace1537f9f699aff258\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_5a70c1436abb7fb7bb081bd667e\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_request\` DROP FOREIGN KEY \`FK_af1eae98b17fa9e92881cafce3d\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_dir_pos\` DROP FOREIGN KEY \`FK_9af2a5b750e303f6a4e5870a443\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_dir_pos\` DROP FOREIGN KEY \`FK_7ef2c34882b3fb18bc366679aa6\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_dir_pos\` DROP FOREIGN KEY \`FK_7a14b7e77f8a819735106b016e5\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` DROP FOREIGN KEY \`FK_73174abf588e8edc848e2e3a121\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` DROP FOREIGN KEY \`FK_3e940da713ea86a9367f70618d0\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` DROP FOREIGN KEY \`FK_1c57c6523dd537b0ef0a9f5b419\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_location\` DROP FOREIGN KEY \`FK_61ea978348ae6a36894bd39de24\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_municipio\` DROP FOREIGN KEY \`FK_9210306e682154252390bb45859\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_parroquia\` DROP FOREIGN KEY \`FK_4ac1c804b1f8dcfc3b08363151f\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_ciudad\` DROP FOREIGN KEY \`FK_41e29c427582948e763288142c1\``);
        await queryRunner.query(`ALTER TABLE \`1000pagosdev\`.\`fm_phone\` DROP FOREIGN KEY \`FK_3796c0f20cddbfce6840776200f\``);
        await queryRunner.query(`DROP INDEX \`IDX_422cda263f57b299d3c85a40bd\` ON \`1000pagosdev\`.\`fm_commerce_photos_fm_photo\``);
        await queryRunner.query(`DROP INDEX \`IDX_7c7ed8c1193d25825291a17646\` ON \`1000pagosdev\`.\`fm_commerce_photos_fm_photo\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_commerce_photos_fm_photo\``);
        await queryRunner.query(`DROP INDEX \`IDX_9d63958d62d8e50a075685c741\` ON \`1000pagosdev\`.\`fm_client_photos_fm_photo\``);
        await queryRunner.query(`DROP INDEX \`IDX_f6c435979c0cb0f36c0694741b\` ON \`1000pagosdev\`.\`fm_client_photos_fm_photo\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_client_photos_fm_photo\``);
        await queryRunner.query(`DROP INDEX \`IDX_5a9520d79b89237a7fbe8e5762\` ON \`1000pagosdev\`.\`fm_client_id_roles_fm_roles\``);
        await queryRunner.query(`DROP INDEX \`IDX_867101050576ea82b6410de17e\` ON \`1000pagosdev\`.\`fm_client_id_roles_fm_roles\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_client_id_roles_fm_roles\``);
        await queryRunner.query(`DROP INDEX \`IDX_309b6bc22137cc95e2efd3f16f\` ON \`1000pagosdev\`.\`fm_worker_roles_fm_roles\``);
        await queryRunner.query(`DROP INDEX \`IDX_4bed12461b5ec1b54453861715\` ON \`1000pagosdev\`.\`fm_worker_roles_fm_roles\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_worker_roles_fm_roles\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_product\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_aci_commerce\``);
        await queryRunner.query(`DROP INDEX \`REL_e74342f2c030e08992c56df0af\` ON \`1000pagosdev\`.\`fm_commerce\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_commerce\``);
        await queryRunner.query(`DROP INDEX \`IDX_97f25df8772b14b2bf67a227e0\` ON \`1000pagosdev\`.\`fm_bank_commerce\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_bank_commerce\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_bank\``);
        await queryRunner.query(`DROP INDEX \`IDX_2b426d3e17a73aa07179aeb223\` ON \`1000pagosdev\`.\`fm_client\``);
        await queryRunner.query(`DROP INDEX \`IDX_15f756dc2a9a6aefe1751f731f\` ON \`1000pagosdev\`.\`fm_client\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_client\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_roles\``);
        await queryRunner.query(`DROP INDEX \`IDX_35eb1f25e7bf89140a2c986b07\` ON \`1000pagosdev\`.\`fm_worker\``);
        await queryRunner.query(`DROP INDEX \`IDX_7a21b1b04b3df8909ad71d8909\` ON \`1000pagosdev\`.\`fm_worker\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_worker\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_department\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_company\``);
        await queryRunner.query(`DROP INDEX \`REL_7af3f0d3b144b7d6a72ceac407\` ON \`1000pagosdev\`.\`fm_request\``);
        await queryRunner.query(`DROP INDEX \`REL_9dd51a6b0f9bc09cd820b0c807\` ON \`1000pagosdev\`.\`fm_request\``);
        await queryRunner.query(`DROP INDEX \`REL_395407df85335f0e00430aa387\` ON \`1000pagosdev\`.\`fm_request\``);
        await queryRunner.query(`DROP INDEX \`REL_4668ebbef8614032e9d58794d4\` ON \`1000pagosdev\`.\`fm_request\``);
        await queryRunner.query(`DROP INDEX \`REL_ecb3a612691fb1e01af12683e3\` ON \`1000pagosdev\`.\`fm_request\``);
        await queryRunner.query(`DROP INDEX \`REL_4f207c9a0e9645910383377f86\` ON \`1000pagosdev\`.\`fm_request\``);
        await queryRunner.query(`DROP INDEX \`REL_b5772edefef68ff71c6477c970\` ON \`1000pagosdev\`.\`fm_request\``);
        await queryRunner.query(`DROP INDEX \`REL_784d15eaace1537f9f699aff25\` ON \`1000pagosdev\`.\`fm_request\``);
        await queryRunner.query(`DROP INDEX \`REL_5a70c1436abb7fb7bb081bd667\` ON \`1000pagosdev\`.\`fm_request\``);
        await queryRunner.query(`DROP INDEX \`REL_af1eae98b17fa9e92881cafce3\` ON \`1000pagosdev\`.\`fm_request\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_request\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_dir_pos\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_location\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_estado\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_municipio\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_parroquia\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_ciudad\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_photo\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_status_request\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_type_request\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_payment_method\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_phone\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_ident_type\``);
        await queryRunner.query(`DROP TABLE \`1000pagosdev\`.\`fm_activity\``);
    }

}
